package ru.nsu.fit.lab4snakepeachblacky.net;

public enum MessageTypes {
    PING, //TO SHOW THAT YOU ARE ALIVE
    ACK, //TO ACK MESSAGES
    STATE, //FROM MASTER TO OTHERS, WITH GAME STATE
    ANNOUNCEMENT, //FROM MULTICAST CONTROLLER, NOTIFICATION ABOUT THE RUNNING GAME
    JOIN, //REQUEST FROM NEW PLAYER TO JOIN GAME
    ERROR, //OP ERROR, FOR EXAMPLE WHEN THERE IS NO FREE SLOTS TO JOIN INTO
}
